---
- name: prepare known_hosts entries
  shell: ssh-keyscan -t rsa {{ item.hostname }}
  with_items: "{{ nodes }}"
  register: keyscans

- name: prepare known_hosts
  lineinfile:
    dest: /home/{{ user }}/.ssh/known_hosts    
    create: yes
    state: present
    line: "{{ item.stdout }}"
    regexp: "{{ item.item.hostname }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items: "{{ keyscans.results }}"

- name: prepare known_hosts entries
  shell: ssh-keyscan -t rsa 0.0.0.0
  register: keyscan_0_0_0_0

- name: add 0.0.0.0 to known_hosts for secondary namenode
  lineinfile:
    dest: /home/{{ user }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ keyscan_0_0_0_0.stdout }}"
    regexp: "0.0.0.0"
    owner: "{{ user }}"
    group: "{{ group }}"