
# Get Master Public Key
- hosts: hadoop-masters 
  become: yes
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_workers.yml
   - vars/nodes.yml
  roles:
    - fetch_public_key

- hosts: hadoop-workers
  become: yes
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_workers.yml
   - vars/nodes.yml
  vars:
    add_user: true
    generate_key: false
    open_firewall: false
    disable_firewall: false
    install_hadoop: true
    config_hadoop: true
    add_known_hosts: false
  roles:
    - user
    - authorized
    - java
    - hadoop


