---
- name: Copy Hive
  copy: src={{ download_path }}/apache-hive-{{hive_version}}-bin.tar.gz dest=/tmp owner={{ user }} mode=755
  
- name: Unzip Hive
  unarchive: 
    src: /tmp/apache-hive-{{hive_version}}-bin.tar.gz
    dest: "{{ hive_path }}"
    remote_src: yes